### ISSUE TITLE
About Performance Benchmark

### ISSUE THREAD

**Issue by flowly** [reborndb/reborn#128]
性能测试数据比较了Twemproxy+Redis还有Reborn-proxy+Reborn-server的性能，在只有一个Proxy的情况下性能就限制于Proxy的性能了，而Twemproxy是单进程的，想问下Reborn-proxy测试的时候go的schedule的线程数目也是设置为1的吗？如果是设置为cpu的core数目的话，那这样测试出来的结果是不是没有那么合理？毕竟没有完全发挥Twemproxy的性能，比如这个时候如果在Twemproxy的机器上再跑一个Twemproxy那性能可能就一致了？

**Comment by siddontang** [comment]
you can see the discussion here https://github.com/wandoulabs/codis/issues/309

Why we develop reborn but not use twemproxy is not for performance in one machine, but for supporting online re-shard dynamically, and twemproxy can not do this. 

btw, twemproxy and reborn are only proxys, they are stateless, so if you meet a bottleneck in one machine, we can scale horizontally easily.

**Comment by flowly** [comment]
额~其实我想表达的是你们这样的benchmark比较，容易误导大家以为reborn-proxy单个的性能比twemproxy好~
