### ISSUE TITLE
更新代码都不试着编辑一下吗？这种错误不应该啊

### ISSUE THREAD

**Issue by weisd** [reborndb/reborn#130]
# github.com/reborndb/reborn/cmd/agent
cmd/agent/proc_proxy.go:30: undefined: erros
cmd/agent/proc_qdb.go:26: undefined: erros
cmd/agent/proc_redis.go:7: imported and not used: "fmt"
godep: go exit status 2

**Comment by siddontang** [comment]
sorry, fixed it.
