### ISSUE TITLE
Is there a benchmark for auto-rebalance?

### ISSUE THREAD

**Issue by neilss** [reborndb/reborn#134]
Here's my step:
1. deploy all instances in single machine
2. init two group, each group with one master reborn-server
3. add 1024 keys(simple key-value, e.g. key_123: 123), which are allocated into two group
4. add one group with one master reborn-server
5. click Auto Rebalance on dashboard
The process of rebalance takes 15 minutes, is this a normal time cost ?

**Comment by siddontang** [comment]
Hi @neilss , we will check it later. 

btw, we don't recommend using auto-balance feature, this is not well supported in reborn, because we have no way to get correct dbsize or keys num in remote qdb servers now. maybe later we will disable this feature. 

Thank you.
