### ISSUE TITLE
tutorial_zh.md build部分少了一个步骤

### ISSUE THREAD

**Issue by lrita** [reborndb/reborn#143]
https://github.com/reborndb/reborn/blob/master/doc/tutorial_zh.md
Build部分

> go get github.com/reborndb/reborn
> cd $GOPATH/src/github.com/reborndb/reborn
> ./bootstrap.sh
> make gotest
> make agent_test (可选, reborn-agent 的集成测试)

./bootstrap.sh下一步少了make

**Comment by siddontang** [comment]
Thanks @lrita 
Can you send us a PR to fix it?
