### ISSUE TITLE
AddServer处缺少参数校验

### ISSUE THREAD

**Issue by lrita** [reborndb/reborn#147]
由于命令reborn-config server add <group_id> <redis_addr> <role>处的<role>对出入并没有进行校验，对应的[此处](https://github.com/reborndb/reborn/blob/master/pkg/models/server_group.go#L279)也没有进行校验，会造成[AddServer](https://github.com/reborndb/reborn/blob/master/pkg/models/server_group.go#L279)此处以错误的server type执行后续逻辑，并给出正确返回，给人错觉。

PS：之前操作role一直输入的是slaver，也没觉察到任何异常，操作也返回200 OK，但是并没有执行slave的逻辑，发现原来是输入错误了....

**Comment by ngaut** [comment]
Could you fire a PR to fix it?
