### ISSUE TITLE
reborndb-agent goroutine泄露的问题

### ISSUE THREAD

**Issue by lrita** [reborndb/reborn#149]
当coordinator为Etcd（{"etcdserver":"2.2.3","etcdcluster":"2.2.0"}）时，启动两个reborndb-agent --ha后，startHA时elector.RunTask产生的leader正常，其他的agent则会goroutine泄露，从而吃掉很多CPU和RAM。
```
11032 @ 0x445d13 0x445dd4 0x41bfaf 0x41bafb 0x6f121d 0x6f0cb2 0x574cdc 0x4768b1
# 0x6f121d    github.com/ngaut/pools.(*ResourcePool).get+0x4ad    /opt/app/src/github.com/reborndb/reborn/Godeps/_workspace/src/github.com/ngaut/pools/resource_pool.go:105
# 0x6f0cb2    github.com/ngaut/pools.(*ResourcePool).Get+0x42     /opt/app/src/github.com/reborndb/reborn/Godeps/_workspace/src/github.com/ngaut/pools/resource_pool.go:84
# 0x574cdc    github.com/ngaut/zkhelper.(*etcdImpl).watch.func1+0x8c  /opt/app/src/github.com/reborndb/reborn/Godeps/_workspace/src/github.com/ngaut/zkhelper/etcd.go:192
```

**Comment by lrita** [comment]
11032 @ 0x445d13 0x445dd4 0x41bfaf 0x41bafb 0x6f121d 0x6f0cb2 0x574cdc 0x4768b1
#	0x6f121d	github.com/ngaut/pools.(*ResourcePool).get+0x4ad	/opt/app/src/github.com/reborndb/reborn/Godeps/_workspace/src/github.com/ngaut/pools/resource_pool.go:105
#	0x6f0cb2	github.com/ngaut/pools.(*ResourcePool).Get+0x42		/opt/app/src/github.com/reborndb/reborn/Godeps/_workspace/src/github.com/ngaut/pools/resource_pool.go:84
#	0x574cdc	github.com/ngaut/zkhelper.(*etcdImpl).watch.func1+0x8c	/opt/app/src/github.com/reborndb/reborn/Godeps/_workspace/src/github.com/ngaut/zkhelper/etcd.go:192

**Comment by siddontang** [comment]
建议先别使用etcd吧，ezkhelper现在用的etcd client都已经是被废弃的了，我们也不准备继续维护。
