### ISSUE TITLE
dashboard上怎么获取proxy的都是主机名，不是已经指定ip了吗？这是bug吗？

### ISSUE THREAD

**Issue by lianfulei** [reborndb/reborn#157]
我启动reborn-proxy的方式是：
cd /usr/local/reborn/src/github.com/reborndb/reborn/sample
nohup ../bin/reborn-proxy -c config.ini --id=proxy_1 -L ./log/proxy_1.log  --cpu=1 --addr=192.168.102.23:19000 --http-addr=192.168.102.23:11000 &

但是启动后：
dashboard上怎么获取proxy的还是主机名，不是已经指定ip了吗？这是bug吗？

![image](https://cloud.githubusercontent.com/assets/12030405/23575435/1ec3fefa-00c7-11e7-97b6-7827ad916f43.png)

**Comment by lianfulei** [comment]
请问这个问题怎么解决？

**Comment by siddontang** [comment]
Sorry, we don't maintain this project now. You can use codis instead.
