### ISSUE TITLE
proxy use a unique random id when starts 

### ISSUE THREAD

**Issue by siddontang** [reborndb/reborn#28]
Now proxy uses pre-defined id like proxy_1, proxy_2 in config file.
Proxy is stateless, so  I think using random id may be more convenient.

**Comment by ngaut** [comment]
By default, proxy use random id. I think we should let  user  set an specific id through command arguments.Which would make it easier to write scripts to manage proxy.

**Comment by siddontang** [comment]
May no need. Later, we will use agent to manage proxy (start, stop or other), and we recommend user using web for OPS. 

@c4pt0r

**Comment by siddontang** [comment]
We must pass a unique proxy id with --id flag and agent will use a random id for starting proxy.
