### ISSUE TITLE
unify ngaut log and reborndb/go/log 

### ISSUE THREAD

**Issue by siddontang** [reborndb/reborn#76]
Use which one? 

Maybe create a new repository forked from ngaut log?
@qiuyesuifeng  @ngaut

**Comment by ngaut** [comment]
Why not just use it directly?
Or fork it to reborn/go ?

**Comment by siddontang** [comment]
qdb use rebondb/go/log 
reborn use ngaut/log

There are two log pkgs here. I think it is not necessary. 

@qiuyesuifeng we may use ngaut/log because it supports rotate log now.

**Comment by qiuyesuifeng** [comment]
ok, got it, i will modify it right now.

**Comment by siddontang** [comment]
Btw, can you disable highlight default, the log looks ugly in editor like 

```
2015/06/13 13:57:40 proc.go:174: [0;37m[info] redis start ok now[0m
```

**Comment by ngaut** [comment]
ngaut/log has api to disable highlight.

**Comment by siddontang** [comment]
Maybe we should disable highlight if we use log file. @qiuyesuifeng

**Comment by qiuyesuifeng** [comment]
yeah. i agreed what u have said, in log no highlight, in console with highlight.
