### ISSUE TITLE
agent redis/qdb data should not be stored in proc base data path

### ISSUE THREAD

**Issue by siddontang** [reborndb/reborn#82]
We may restart qdb/redis gracefully, at that time, the proc id will be changed, but the new server must use the old data.

maybe the data path like agent_data/qdb_addr may be better, because we will use a fix address for qdb/redis. 

@qiuyesuifeng

**Comment by qiuyesuifeng** [comment]
see #90, i am not sure whether it is the right way to process old log and data, we can discuss for it.

**Comment by qiuyesuifeng** [comment]
add a new pr, see #108
